version: '3.8'
services:
  cosmos:
    build:
      context: ./cosmos
    ports:
      - "26657:26657"
      - "1317:1317"
    volumes:
      - cosmos-data:/root/.cosmosd
    command: cosmosd start

  cronos:
    build:
      context: ./cronos
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - cronos-data:/root/.cronos
    command: cronosd start

  api:
    build:
      context: ./api
    ports:
      - "4000:4000"
    depends_on:
      - cosmos
      - cronos

volumes:
  cosmos-data:
  cronos-data:
