version: '3.8'
services:
  cosmos:
    build:
      context: ./cosmos
    ports:
      - "26657:26657"
      - "1317:1317"
    volumes:
      - cosmos-data:/root/.cosmosd
    # Using the CMD from Dockerfile
    networks:
      - did-network

  cronos:
    build:
      context: ./cronos
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - cronos-data:/root/.cronos
    # Using the CMD from Dockerfile
    networks:
      - did-network

  ipfs:
    image: ipfs/kubo:latest
    ports:
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ipfs-data:/data/ipfs
    networks:
      - did-network

  api:
    build:
      context: ./api
    ports:
      - "4000:4000"
    depends_on:
      - cosmos
      - cronos
      - ipfs
      - ipfs-eu-1
      - ipfs-eu-2
      - ipfs-us-1
      - ipfs-us-2
    environment:
      - COSMOS_API=http://cosmos:1317
      - CRONOS_RPC=http://cronos:8545
      - IPFS_API=http://ipfs:5001
      - JWT_SECRET=your-jwt-secret-key-change-in-production
      - PORT=4000
      - REGION=EU
      - BOOTSTRAP_LIST=/ip4/ipfs-eu-1/tcp/4001/p2p/QmEU1,/ip4/ipfs-eu-2/tcp/4001/p2p/QmEU2,/ip4/ipfs-us-1/tcp/4001/p2p/QmUS1,/ip4/ipfs-us-2/tcp/4001/p2p/QmUS2
      - EU_MIDDLEWARE_PEER_ID=12D3KooWE5b3VqbmaKj7D4u5R9wygV3z9uNT7UUFvmWA6QTy7x1A
      - US_MIDDLEWARE_PEER_ID=12D3KooWF6b3VqbmaKj7D4u5R9wygV3z9uNT7UUFvmWA6QTy7x1B
    volumes:
      - ./api/client:/app/client
    networks:
      - did-network

  ipfs-eu-1:
    image: ipfs/kubo:latest
    ports:
      - "5011:5001"  # Changed from 5001:5001 to avoid port conflict
      - "4001:4001"
    volumes:
      - ipfs-eu-1-data:/data/ipfs
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data/ipfs
    networks:
      - did-network

  ipfs-eu-2:
    image: ipfs/kubo:latest
    ports:
      - "5002:5001"
      - "4002:4001"
    volumes:
      - ipfs-eu-2-data:/data/ipfs
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data/ipfs
    networks:
      - did-network

  ipfs-us-1:
    image: ipfs/kubo:latest
    ports:
      - "5003:5001"
      - "4003:4001"
    volumes:
      - ipfs-us-1-data:/data/ipfs
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data/ipfs
    networks:
      - did-network

  ipfs-us-2:
    image: ipfs/kubo:latest
    ports:
      - "5004:5001"
      - "4004:4001"
    volumes:
      - ipfs-us-2-data:/data/ipfs
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data/ipfs
    networks:
      - did-network

networks:
  did-network:
    driver: bridge

volumes:
  cosmos-data:
  cronos-data:
  ipfs-data:
  ipfs-eu-1-data:
  ipfs-eu-2-data:
  ipfs-us-1-data:
  ipfs-us-2-data: