# This file configures the Cosmos SDK node.

moniker = "cosmos-did-node"
chain-id = "cosmos-did-devnet"

[rpc]
  laddr = "tcp://0.0.0.0:26657"

[p2p]
  laddr = "tcp://0.0.0.0:26656"
  seed_mode = false

[consensus]
  timeout_commit = "1s"

[tx_index]
  indexer = "kv"
